export const resolvedActionTypes = {
    GET_RESOLVED_START: 'GET_RESOLVED_START',
    GET_RESOLVED_SUCCESS: 'GET_RESOLVED_SUCCESS',
    GET_RESOLVED_FAILURE: 'GET_RESOLVED_FAILURE',
    SET_RESOLVED_PREV_DOC: 'SET_RESOLVED_PREV_DOC',
    GET_MORE_RESOLVED_START: 'GET_MORE_RESOLVED_START',
    GET_MORE_RESOLVED_SUCCESS: 'GET_MORE_RESOLVED_SUCCESS',
    GET_MORE_RESOLVED_FAILURE: 'GET_MORE_RESOLVED_FAILURE'
}