export const pendingActionTypes = {
    GET_PENDING_START: 'GET_PENDING_START',
    GET_PENDING_SUCCESS: 'GET_PENDING_SUCCESS',
    GET_PENDING_FAILURE: 'GET_PENDING_FAILURE',
    SET_PENDING_PREV_DOC: 'SET_PENDING_PREV_DOC',
    GET_MORE_PENDING_START: 'GET_MORE_PENDING_START',
    GET_MORE_PENDING_SUCCESS: 'GET_MORE_PENDING_SUCCESS',
    GET_MORE_PENDING_FAILURE: 'GET_MORE_PENDING_FAILURE'
}